# Generated by Django 3.2 on 2022-04-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220409_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='prifile_image',
            new_name='profile_image',
        ),
    ]
